Use typescript to parse tsconfig.json
davestewart/alias-hq pull request #37
Opened 2021-11-25 03:55 UTC by IanVS

I'll write some tests for comments and trailing commas in config files, but this seems like a promising approach.

2021-11-25 03:57 UTC, davestewart commented
Looks good!

It's late here so I'll take a look tomorrow.

Thanks :)

2021-11-25 12:57 UTC, davestewart requested changes
All good! Just some code style changes, thanks :)

2021-11-25 12:57 UTC, davestewart commented on src/index.js
> +const ts = require('typescript')
Can you name this `Ts` (cap T) and move to top of file

2021-11-25 12:57 UTC, davestewart commented on src/index.js
> +  const {config, error} = ts.parseConfigFileTextToJson(path, text)
I haven't added any linting to this project yet (will do that). I use Standard JS with Stroustrop brackets, so:

- spaces round deconstruction braces please
- else on newline

2021-11-25 12:57 UTC, davestewart commented on src/index.js
> +  const {config: json, error} = ts.parseConfigFileTextToJson(path, text)
spaces round brackets please

2021-11-25 12:57 UTC, davestewart commented on src/index.js
> +    config.rootUrl = compilerOptions.pathsBasePath || Path.dirname(path);
No terminating semis

2021-11-25 12:57 UTC, davestewart commented on tests/specs/load.spec.js
> +      expect(received.config.paths).toEqual(expected);
No semis, thanks

2021-11-25 14:08 UTC, davestewart commented
OK, linting now added so you'll want to merge and run `npm run lint`.

2021-11-25 16:28 UTC, IanVS commented
Updated to address linting issues

2021-11-25 16:57 UTC, davestewart approved these changes

2021-11-25 16:59 UTC, davestewart commented
No idea what these errors are about. Any ideas?

2021-11-25 17:07 UTC, merged

2022-09-21 12:04 UTC, davestewart commented
Just reviewing this as I need it today!

This lib came up in my Google search:

- https://github.com/TypeStrong/tsconfig

I'll probably look to implement it...